# Buster is the glibc floor donor: the oldest base still worth supporting.
# The platform pin matters even on an arm64 workstation, because the shell
# completions below are generated by executing the amd64 binary.
FROM --platform=linux/amd64 docker.io/library/debian:buster AS build

RUN sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list && \
    sed -i '/security.debian.org/d' /etc/apt/sources.list && \
    echo "Acquire::Check-Valid-Until false;" > /etc/apt/apt.conf.d/99no-check-valid-until

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gcc \
    libc6-dev \
    gcc-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    && rm -rf /var/lib/apt/lists/*

ENV CARGO_HOME=/usr/local/cargo \
    RUSTUP_HOME=/usr/local/rustup \
    PATH=/usr/local/cargo/bin:$PATH
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --no-modify-path
RUN rustup target add x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu

ENV CC_x86_64_unknown_linux_gnu=x86_64-linux-gnu-gcc \
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-linux-gnu-gcc \
    CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc \
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY src ./src

# Every dependency of the .deb's Depends: line is read off the binaries here
# rather than written into packaging/control: a glibc floor set too low
# installs cleanly and then dies at exec on a symbol version, and a hardcoded
# soname list silently under-declares as soon as a crate links something new.
# /app/target is a cache mount, so everything the package needs must be copied
# into /out before this layer ends.
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=cargo-target,target=/app/target \
    set -eu; \
    mkdir -p /out/completions; \
    for target in x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu; do \
        cargo build --release --locked --target "$target"; \
    done; \
    strip -o /out/claude-conversation-search.amd64 \
        target/x86_64-unknown-linux-gnu/release/claude-conversation-search; \
    aarch64-linux-gnu-strip -o /out/claude-conversation-search.arm64 \
        target/aarch64-unknown-linux-gnu/release/claude-conversation-search; \
    for shell in bash zsh fish; do \
        /out/claude-conversation-search.amd64 completions "$shell" > "/out/completions/$shell"; \
    done; \
    for arch in amd64 arm64; do \
        binary="/out/claude-conversation-search.$arch"; \
        readelf -W --dyn-syms "$binary" \
          | sed -n 's/.*GLIBC_\([0-9][0-9.]*\).*/\1/p' \
          | sort -Vu | tail -1 > "/out/glibc-floor.$arch"; \
        test -s "/out/glibc-floor.$arch" || { echo "no GLIBC symbol version in $binary" >&2; exit 1; }; \
        : > "/out/depends-extra.$arch"; \
        sonames=$(readelf -Wd "$binary" | sed -n 's/.*(NEEDED).*\[\(.*\)\]/\1/p'); \
        for soname in $sonames; do \
            case "$soname" in \
                libc.so.6|libm.so.6|libdl.so.2|libpthread.so.0|librt.so.1) ;; \
                ld-linux-x86-64.so.2|ld-linux-aarch64.so.1) ;; \
                libgcc_s.so.1) printf ', libgcc-s1' >> "/out/depends-extra.$arch" ;; \
                *) echo "$binary needs $soname, which maps to no known package" >&2; exit 1 ;; \
            esac; \
        done; \
    done

FROM scratch
COPY --from=build /out/ /
